package it.dpascotto.drools.tictactoe

import org.apache.log4j.Logger;

global Logger log;
global String player;

//
//	Defending rows
//
rule "Defend rows"
dialect "java"
no-loop
salience 2

when
	ttt : TicTacToeGame(isUpTo(player))
then
	for (int r = 0; r < 3; r++) {
		int e = ttt.getFirstEmpty(ttt.getRow(r), 2, ttt.otherPlayer(player));
		if (e >= 0) {
			log.debug("Defending in " + r + ", " + e);
			ttt.move(player, r, e);
			update(ttt);
			break;
		}		
	}
end



//
//	Defending columns
//

rule "Defend columns"
dialect "java"
no-loop
salience 2

when
	ttt : TicTacToeGame(isUpTo(player))
then
	for (int c = 0; c < 3; c++) {
		int e = ttt.getFirstEmpty(ttt.getCol(c), 2, ttt.otherPlayer(player));
		if (e >= 0) {
			log.debug("Defending in " + e + ", " + c);
			ttt.move(player, e, c);
			update(ttt);
			break;
		}		
	}	
end



//
//	Defending diagonals
//

rule "Defends diagonal 1"
dialect "java"
no-loop
salience 2

when
	ttt : TicTacToeGame(isUpTo(player))
then
	int e = ttt.getFirstEmpty(ttt.getDiagonal1(), 2, ttt.otherPlayer(player));
	if (e >= 0) {
		log.debug("Defending in " + e + ", " + e);
		ttt.move(player, e, e);
		update(ttt);
	}		
end

rule "Defends diagonal 2"
dialect "java"
no-loop
salience 2

when
	ttt : TicTacToeGame(isUpTo(player))
then
	int e = ttt.getFirstEmpty(ttt.getDiagonal2(), 2, ttt.otherPlayer(player));
	if (e >= 0) {
		log.debug("Defending in " + e + ", " + (2 - e));
		ttt.move(player, e, (2 - e));
		update(ttt);
	}		
end



